var listaAnimales=[
{
id:1,
nombre:'Aguila',
descripcion:'Ave Rapaz 1',
imagen:'aguila.jpg',
seccion:'avesRapaces',
precio:12.5,
duracion:10,
},
{
id:2,
nombre:'Buitre',
descripcion:'Ave Rapaz 2',
imagen:'buitre.jpg',
seccion:'avesRapaces',
precio:10.5,
duracion:10,
},
{
id:3,
nombre:'Halcon',
descripcion:'Ave Rapaz 3',
imagen:'halcon.jpg',
seccion:'avesRapaces',
precio:12.5,
duracion:10,
},
{
id:4,
nombre:'Leon marino',
descripcion:'Bahia steller 1',
imagen:'leonMarino.jpg',
seccion:'bahiaSteller',
precio:2.5,
duracion:20,
},
{
id:6,
nombre:'Lemur Blanco',
descripcion:'Bosque africano 1',
imagen:'lemurBlanco.jpg',
seccion:'bosqueAfricano',
precio:5.5,
duracion:30,
},
{
id:7,
nombre:'Lemures',
descripcion:'Bosque africano 2',
imagen:'lemures.jpg',
seccion:'bosqueAfricano',
precio:5.5,
duracion:30,
},
{
id:8,
nombre:'Lemur Raton',
descripcion:'Bosque africano 3',
imagen:'lemurRaton.jpg',
seccion:'bosqueAfricano',
precio:5.5,
duracion:30,
},
{
id:9,
nombre:'Lemur Rojo',
descripcion:'Bosque africano 4',
imagen:'lemurRojo.jpg',
seccion:'bosqueAfricano',
precio:6.5,
duracion:30,
},
{
id:10,
nombre:'Mazama',
descripcion:'Bosque templado 1',
imagen:'mazama.jpg',
seccion:'bosqueTemplado',
precio:5.5,
duracion:30,
},
{
id:11,
nombre:'Mazama2',
descripcion:'Bosque templado 2',
imagen:'mazama2.jpg',
seccion:'bosqueTemplado',
precio:5.5,
duracion:30,
},
{
id:12,
nombre:'Munjat',
descripcion:'Bosque templado 4',
imagen:'munjat.jpg',
seccion:'bosqueTemplado',
precio:5.5,
duracion:30,
},
{
id:13,
nombre:'Muntjac',
descripcion:'Bosque templado 4',
imagen:'muntjac.jpg',
seccion:'bosqueTemplado',
precio:5.5,
duracion:30,
},
{
id:15,
nombre:'Arapaima',
descripcion:'jungla 1',
imagen:'arapaima.jpg',
seccion:'jungla',
precio:5.5,
duracion:40,
},
{
id:16,
nombre:'Manati',
descripcion:'jungla 2',
imagen:'manati.jpg',
seccion:'jungla',
precio:5.5,
duracion:40,
},
{
id:17,
nombre:'Mono',
descripcion:'jungla 3',
imagen:'mono.jpg',
seccion:'jungla',
precio:5.5,
duracion:40,
},
{
id:18,
nombre:'Titi',
descripcion:'jungla 4',
imagen:'titi.jpg',
seccion:'jungla',
precio:5.5,
duracion:40,
},
{
id:19,
nombre:'Tucan',
descripcion:'jungla 5',
imagen:'tucan.jpg',
seccion:'jungla',
precio:5.5,
duracion:40,
},
{
id:20,
nombre:'Pinguino Adelia',
descripcion:'polos 1',
imagen:'pinguinoAdelia.jpg',
seccion:'polos',
precio:7.5,
duracion:50,
},
{
id:21,
nombre:'Pinguino Barbijo',
descripcion:'polos 2',
imagen:'pinguinoBarbijjo.jpg',
seccion:'polos',
precio:7.5,
duracion:50,
},
{
id:22,
nombre:'Pinguino Humboldt',
descripcion:'polos 3',
imagen:'pinguinoHumboldt.jpg',
seccion:'polos',
precio:7.5,
duracion:50,
},
{
id:23,
nombre:'Pinguino Papua',
descripcion:'polos 4',
imagen:'pinguinoPapua.jpg',
seccion:'polos',
precio:7.5,
duracion:50,
},
{
id:30,
nombre:'Caballito de mar',
descripcion:'sombras 1',
imagen:'caballitoMar.jpg',
seccion:'sombras',
precio:7.5,
duracion:60,
},
{
id:31,
nombre:'Galago',
descripcion:'sombras 2',
imagen:'galago.jpg',
seccion:'sombras',
precio:7.5,
duracion:60,
},
{
id:32,
nombre:'Piton',
descripcion:'sombras 3',
imagen:'piton.jpg',
seccion:'sombras',
precio:7.5,
duracion:60,
},
{
id:33,
nombre:'Tetra Ciego',
descripcion:'sombras 4',
imagen:'tetraCiego.jpg',
seccion:'sombras',
precio:7.5,
duracion:60,
}
]

